language: node_js
node_js:
  - '0.10'
before_script:
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'npm install karma-jasmine'
  - 'npm install karma-chrome-launcher'
  - 'bower install'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'grunt build'
